CC = cc //for 'cc'
FLAGS = -Wall -Wextra -Werror -I include //for flags for comp.



.PHONY: help, start
help:
	@echo "you can choose, but only one: "
	@echo " help"
	@echo " start"

start:
	@echo "Makefile is working!"
	@echo "Ledies and Gentlemen start your engines!"
